apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubernetes-db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: "/data/dbs-local-storage/kubernetes-db"